# AUTOGENERATED FROM 'src/blog/service_layer/queries/create_blog.edgeql' WITH:
#     $ edgedb-py -d blog_db


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateBlogResult(NoPydanticValidation):
    id: uuid.UUID
    title: str
    content: str
    author: str
    comments: list[str]


async def create_blog(
    executor: edgedb.AsyncIOExecutor,
    *,
    title: str,
    content: str,
    author: str,
    comments: str,
) -> CreateBlogResult:
    return await executor.query_single(
        """\
        with title:=<str>$title,
            content:=<str>$content,
            author:=<str>$author,
            comments:=<str>$comments,
            select(
                insert Blog{
                    title:=title,
                    content:=content,
                    author:=author,
                    comments:=comments,
                }
            )
            {
                id,
                title,
                content,
                author,
                comments
            }\
        """,
        title=title,
        content=content,
        author=author,
        comments=comments,
    )
